version: '3.8' # The 'version' attribute is considered obsolete in newer Docker Compose versions, but it's fine to keep for compatibility. You can remove it if you wish.

services:
  ciroh-rag:
    build: .
    container_name: ciroh-rag-system
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./cache:/app/cache
    mem_limit: 8g
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Embedding model configuration with default values if not set in host environment
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME:-all-MiniLM-L6-v2}
      - EMBEDDING_DIM=${EMBEDDING_DIM:-384}
      # LLM configuration with default values
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-gpt-3.5-turbo}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
      - LLM_MAX_TOKENS_CONTEXT=${LLM_MAX_TOKENS_CONTEXT:-4000}
      - LLM_MAX_TOKENS_RESPONSE=${LLM_MAX_TOKENS_RESPONSE:-1000}
      # Document processing settings with default values
      - TARGET_CHUNK_SIZE_TOKENS=${TARGET_CHUNK_SIZE_TOKENS:-512}
      - CHUNK_OVERLAP_SENTENCES=${CHUNK_OVERLAP_SENTENCES:-2}
      - MIN_CHUNK_SIZE_TOKENS=${MIN_CHUNK_SIZE_TOKENS:-20}
      # Storage paths, ensuring consistency between Dockerfile and Compose
      - STORAGE_PATH=${STORAGE_PATH:-./storage}
      - DATA_PATH=${DATA_PATH:-./data}
      # Cache settings with default values
      - ENABLE_CACHE=${ENABLE_CACHE:-true}
      - CACHE_DIR=${CACHE_DIR:-./cache}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-10}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-60}
      - CACHE_VALIDITY_DAYS=${CACHE_VALIDITY_DAYS:-1}
      # SpaCy model to be used by the application
      - SPACY_MODEL=${SPACY_MODEL:-en_core_web_sm}
      # NEW: Control knowledge graph visualization generation
      - GENERATE_KG_VISUALIZATION=${GENERATE_KG_VISUALIZATION:-true}
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 --timeout 300 web_server:app

volumes:
  data:
  storage:
  cache: