services:
  ciroh-rag:
    build: .
    container_name: ciroh-rag-system
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./cache:/app/cache
    environment:
      # Use key: value map style for environment variables
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEO4J_URI: ${NEO4J_URI:-bolt://neo4j:7687}
      NEO4J_USERNAME: ${NEO4J_USERNAME:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-12345678} # Change this strong password!
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-all-MiniLM-L6-v2}
      EMBEDDING_DIM: ${EMBEDDING_DIM:-384}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME:-gpt-3.5-turbo}
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.7}
      LLM_MAX_TOKENS_CONTEXT: ${LLM_MAX_TOKENS_CONTEXT:-4000}
      LLM_MAX_TOKENS_RESPONSE: ${LLM_MAX_TOKENS_RESPONSE:-1000}
      TARGET_CHUNK_SIZE_TOKENS: ${TARGET_CHUNK_SIZE_TOKENS:-512}
      CHUNK_OVERLAP_SENTENCES: ${CHUNK_OVERLAP_SENTENCES:-2}
      MIN_CHUNK_SIZE_TOKENS: ${MIN_CHUNK_SIZE_TOKENS:-20}
      STORAGE_PATH: ${STORAGE_PATH:-./storage}
      DATA_PATH: ${DATA_PATH:-./data}
      ENABLE_CACHE: ${ENABLE_CACHE:-true}
      CACHE_DIR: ${CACHE_DIR:-./cache}
      MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS:-10}
      REQUEST_TIMEOUT: ${REQUEST_TIMEOUT:-60}
      CACHE_VALIDITY_DAYS: ${CACHE_VALIDITY_DAYS:-1}
      SPACY_MODEL: ${SPACY_MODEL:-en_core_web_sm}
      GENERATE_KG_VISUALIZATION: ${GENERATE_KG_VISUALIZATION:-true}
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 --timeout 300 web_server:app

  neo4j:
    image: neo4j:5.20.0-community
    container_name: neo4j_db
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt port
    volumes:
      - ./neo4j_data:/data
    environment:
      # --- THIS IS THE FINAL CORRECTED SECTION ---
      # Ensure there's NO hyphen before NEO4J_PLUGINS: >-
      # This entire 'environment' section for neo4j_db should be a YAML map (dictionary)
      # where keys are indented and followed by a colon.
      NEO4J_PLUGINS: >-
        ["apoc"]
      NEO4J_AUTH: ${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-password}
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_memory_pagecache_size: 512M
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    restart: unless-stopped

volumes:
  data:
  storage:
  cache:
  neo4j_data: